version: "3.9"

services:
  caddy:
    image: caddy:2.8
    restart: unless-stopped
    ports: ["80:80"]
    volumes:
      - /home/ec2-user/ops/Caddyfile:/etc/caddy/Caddyfile:ro
      - /srv/admin/current:/srv/admin/current:ro
      - /srv/front/current:/srv/front/current:ro
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1/health"]
      interval: 10s
      timeout: 3s
      retries: 10
    logging:
      driver: json-file
      options: { max-size: "10m", max-file: "3" }

  grafana:
    image: grafana/grafana:10.4.5
    restart: unless-stopped
    user: "472:0"
    environment:
      - GF_SERVER_ROOT_URL=/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - grafana-data:/var/lib/grafana
    expose: ["3000"]

  prometheus:
    image: prom/prometheus:v2.54.1
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=15d"
      - "--web.enable-lifecycle"
      - "--web.external-url=https://monitor.toky.devkor.club/prometheus/"
      - "--web.route-prefix=/prometheus"
    volumes:
      - /home/ec2-user/ops/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prom-data:/prometheus
      - /etc/prometheus/targets:/etc/prometheus/targets:ro
      - /home/ec2-user/ops/secrets:/etc/prometheus/secrets:ro
    ports:
      - "127.0.0.1:9090:9090"

volumes:
  grafana-data: {}
  prom-data: {}
