global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node-exporter-app'
    file_sd_configs:
      - files:
          - /etc/prometheus/targets/node-exporter.json
    scheme: http
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        regex: '([^:]+):?.*'
        target_label: host
        replacement: '$1'
      - action: labeldrop
        regex: '^(role|svc|type)$'
    metric_relabel_configs:
      - action: labeldrop
        regex: '^(role|svc|type)$'

  - job_name: 'nest-app'
    file_sd_configs:
      - files:
          - /etc/prometheus/targets/nest-app.json
    scheme: http
    metrics_path: /metrics
    basic_auth:
      username: metrics
      password_file: /etc/prometheus/secrets/nest-app-basic-password
    relabel_configs:
      - source_labels: [__address__]
        regex: '([^:]+):?.*'
        target_label: host
        replacement: '$1'
      - action: labeldrop
        regex: '^(role|svc|type)$'
    metric_relabel_configs:
      - action: labeldrop
        regex: '^(role|svc|type)$'